# Generated by Django 5.2.7 on 2025-10-25 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration parameters, templates, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parameters used for this report run')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='reports.reportdefinition')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum of the file', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='reports.reportrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['definition', 'requested_at'], name='reports_rep_definit_fb833f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['status'], name='reports_rep_status_f320b8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportartifact',
            index=models.Index(fields=['report_run'], name='reports_rep_report__ec9b00_idx'),
        ),
        migrations.AddIndex(
            model_name='reportartifact',
            index=models.Index(fields=['created_at'], name='reports_rep_created_6e02b9_idx'),
        ),
    ]
