# Generated by Django 5.2.7 on 2025-10-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_active',
        ),
    ]
