# Generated by Django 5.2.7 on 2025-10-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
